language: node_js
node_js: stable
os: linux
dist: trusty
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/hearthdb
  fqdn: andreferreira.tech
  on:
    branch: master
